###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: convertr-code-test-redis

    mysql:
      image: mysql:5.7
      container_name: convertr-code-test-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=pass
        - MYSQL_DATABASE=test
        - MYSQL_USER=user
        - MYSQL_PASSWORD=pass
      ports:
        - "1027:3306"

    webserver:
      image: nginx:alpine
      container_name: convertr-code-test-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "1025:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: convertr-code-test-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

